import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "@/components/context/theme-provider";
import store from "./store/store";
import { setLoading, setUser } from "./store/slices/authSlices";
import { cookies } from "next/headers";
import { getSessionData } from "../../actions/storedData/methods";
import TopScroller from "@/components/ScrollToTop";
import { Toaster } from "@/components/ui/sonner";
import LoaderSpinner from "@/components/LoaderSpinner";
import QueryProviders from "@/lib/cachingProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

const inter = Inter({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Skill Studio - Learn Anything, Anywhere, Anytime | Certificates & Online Courses",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userData = await getSessionData()
  store.dispatch({ type: "auth/setUser", payload:userData?.user})

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link
        rel="icon"
        href="/skillstudioicon.png"
      />
      </head>
      <body
        className={`${inter.className} antialiased whitespace-nowrap`}
      >
        <ThemeProvider
          attribute="class"
          forcedTheme="light"
          disableTransitionOnChange
        >
          <QueryProviders>
            
        <Providers>
        <Toaster />
        <LoaderSpinner/>
          <TopScroller/>
          {children}
        </Providers>
          </QueryProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
